import React, { useState, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { generatePlaylistTracks, derivePlaylistName } from '../services/gemini';
import {
  getCurrentUserId,
  searchAllTracks,
  createPlaylist,
  addTracksToPlaylist,
} from '../services/spotify';
import PromptInput from '../components/PromptInput';
import TrackList from '../components/TrackList';
import LoadingSpinner from '../components/LoadingSpinner';
import PlaylistResult from '../components/PlaylistResult';

/**
 * Application state machine states.
 */
const STATUS = {
  IDLE: 'IDLE',
  LOADING_AI: 'LOADING_AI',
  LOADING_SPOTIFY: 'LOADING_SPOTIFY',
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
};

/**
 * CreatePage — the main app screen after login.
 * Manages the full playlist generation flow.
 */
export default function CreatePage() {
  const { accessToken, logout } = useAuth();
  const navigate = useNavigate();

  const [status, setStatus] = useState(STATUS.IDLE);
  const [tracks, setTracks] = useState([]);
  const [playlistUrl, setPlaylistUrl] = useState(null);
  const [playlistName, setPlaylistName] = useState('');
  const [trackCount, setTrackCount] = useState(0);
  const [errorMessage, setErrorMessage] = useState('');
  const [searchProgress, setSearchProgress] = useState({ current: 0, total: 0 });

  /**
   * Handles unauthorized errors by clearing token and redirecting to login.
   */
  const handleUnauthorized = useCallback(() => {
    logout();
    navigate('/');
  }, [logout, navigate]);

  /**
   * Main handler — orchestrates the full AI → Spotify pipeline.
   */
  const handleGenerate = async (prompt) => {
    setStatus(STATUS.LOADING_AI);
    setTracks([]);
    setErrorMessage('');
    setPlaylistUrl(null);
    setSearchProgress({ current: 0, total: 0 });

    try {
      // Step 1: Ask Gemini for tracks
      const aiTracks = await generatePlaylistTracks(prompt);
      setTracks(aiTracks);

      // Step 2: Switch to Spotify loading phase
      setStatus(STATUS.LOADING_SPOTIFY);
      setSearchProgress({ current: 0, total: aiTracks.length });

      try {
        // Step 3: Get current user ID
        const userId = await getCurrentUserId(accessToken);

        // Step 4: Search tracks sequentially
        const uris = await searchAllTracks(aiTracks, accessToken, (current, total) => {
          setSearchProgress({ current, total });
        });

        if (uris.length === 0) {
          throw new Error("Couldn't find any of the suggested songs on Spotify. Try a different prompt.");
        }

        // Step 5: Derive playlist name
        const name = derivePlaylistName(prompt);
        setPlaylistName(name);

        // Step 6: Create playlist
        const description = `Generated by AI from prompt: "${prompt}"`;
        const playlist = await createPlaylist(name, description, accessToken);

        // Step 7: Add tracks
        await addTracksToPlaylist(playlist.id, uris, accessToken);

        // Step 8: Success!
        setPlaylistUrl(playlist.external_urls.spotify);
        setTrackCount(uris.length);
        setStatus(STATUS.SUCCESS);
      } catch (err) {
        console.error('Spotify Flow Error:', err);
        if (err.message === 'SPOTIFY_PREMIUM_REQUIRED') {
          setTrackCount(aiTracks.length);
          setStatus(STATUS.SUCCESS);
          setErrorMessage('Note: Spotify still reports "Premium Required". Please try logging out and back in.');
        } else {
          // Show the actual error message from Spotify
          setErrorMessage(`Spotify Error: ${err.message}`);
          setStatus(STATUS.ERROR);
        }
      }
    } catch (err) {
      console.error('Gemini/General Error:', err);
      if (err.message === 'SPOTIFY_UNAUTHORIZED') {
        handleUnauthorized();
        return;
      }
      setErrorMessage(err.message || 'Something went wrong. Please try again.');
      setStatus(STATUS.ERROR);
    }
  };

  /**
   * Resets back to IDLE so the user can try again.
   */
  const handleReset = () => {
    setStatus(STATUS.IDLE);
    setTracks([]);
    setPlaylistUrl(null);
    setPlaylistName('');
    setErrorMessage('');
  };

  const isLoading = status === STATUS.LOADING_AI || status === STATUS.LOADING_SPOTIFY;

  return (
    <div className="gradient-bg min-h-screen flex flex-col">
      {/* Floating orbs */}
      <div
        className="fixed top-0 right-0 w-[500px] h-[500px] rounded-full pointer-events-none"
        style={{
          background: 'radial-gradient(circle, rgba(29,185,84,0.08) 0%, transparent 70%)',
          filter: 'blur(60px)',
          transform: 'translate(30%, -30%)',
        }}
      />

      {/* Header */}
      <header className="flex items-center justify-between px-6 py-5 z-10">
        <div className="flex items-center gap-3">
          <div
            className="w-9 h-9 rounded-full flex items-center justify-center"
            style={{ background: '#1DB954' }}
          >
            <svg width="18" height="18" viewBox="0 0 24 24" fill="#000">
              <path d="M12 0C5.4 0 0 5.4 0 12s5.4 12 12 12 12-5.4 12-12S18.66 0 12 0zm5.521 17.34c-.24.359-.66.48-1.021.24-2.82-1.74-6.36-2.101-10.561-1.141-.418.122-.779-.179-.899-.539-.12-.421.18-.78.54-.9 4.56-1.021 8.52-.6 11.64 1.32.42.18.479.659.301 1.02zm1.44-3.3c-.301.42-.841.6-1.262.3-3.239-1.98-8.159-2.58-11.939-1.38-.479.12-1.02-.12-1.14-.6-.12-.48.12-1.021.6-1.141C9.6 9.9 15 10.561 18.72 12.84c.361.181.54.78.241 1.2zm.12-3.36C15.24 8.4 8.82 8.16 5.16 9.301c-.6.179-1.2-.181-1.38-.721-.18-.601.18-1.2.72-1.381 4.26-1.26 11.28-1.02 15.721 1.621.539.3.719 1.02.419 1.56-.299.421-1.02.599-1.559.3z"/>
            </svg>
          </div>
          <span className="font-bold text-white text-sm tracking-tight">AI Playlist Generator</span>
        </div>

        <button
          id="logout-btn"
          onClick={handleUnauthorized}
          className="text-xs font-medium transition-colors duration-150 px-3 py-1.5 rounded-full cursor-pointer border-none"
          style={{
            background: 'rgba(255,255,255,0.07)',
            color: '#B3B3B3',
          }}
          onMouseEnter={(e) => {
            e.currentTarget.style.background = 'rgba(255,255,255,0.12)';
            e.currentTarget.style.color = '#fff';
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.background = 'rgba(255,255,255,0.07)';
            e.currentTarget.style.color = '#B3B3B3';
          }}
        >
          Disconnect
        </button>
      </header>

      {/* Main content */}
      <main className="flex-1 flex flex-col items-center justify-start px-6 py-8 z-10">
        <div className="w-full max-w-xl flex flex-col gap-8">

          {/* Page title — only show when idle/error */}
          {(status === STATUS.IDLE || status === STATUS.ERROR) && (
            <div className="fade-in-up">
              <h1 className="text-4xl font-black text-white mb-2 tracking-tight leading-tight">
                What's the vibe?
              </h1>
              <p className="text-base" style={{ color: '#B3B3B3' }}>
                Describe a mood, moment, or theme and we'll generate the perfect playlist.
              </p>
            </div>
          )}

          {/* Prompt input — always shown unless loading/success */}
          {(status === STATUS.IDLE || status === STATUS.ERROR) && (
            <div className="glass-card p-6 fade-in-up">
              <PromptInput onSubmit={handleGenerate} disabled={isLoading} />
            </div>
          )}

          {/* Error message */}
          {status === STATUS.ERROR && (
            <div
              className="rounded-xl px-5 py-4 flex items-start gap-3 fade-in-up"
              style={{
                background: 'rgba(239,68,68,0.1)',
                border: '1px solid rgba(239,68,68,0.25)',
              }}
            >
              <svg width="20" height="20" viewBox="0 0 24 24" fill="#ef4444" className="flex-shrink-0 mt-0.5">
                <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z"/>
              </svg>
              <div>
                <p className="text-sm font-semibold text-white mb-0.5">Something went wrong</p>
                <p className="text-sm" style={{ color: '#fca5a5' }}>{errorMessage}</p>
              </div>
            </div>
          )}

          {/* Loading — AI phase */}
          {status === STATUS.LOADING_AI && (
            <div className="glass-card p-8 fade-in-up">
              <LoadingSpinner message="Thinking about your playlist…" />
            </div>
          )}

          {/* Loading — Spotify phase */}
          {status === STATUS.LOADING_SPOTIFY && (
            <div className="glass-card p-8 fade-in-up flex flex-col gap-6">
              <LoadingSpinner
                message="Building your playlist…"
                progress={searchProgress.current}
                total={searchProgress.total}
              />
              {tracks.length > 0 && <TrackList tracks={tracks} />}
            </div>
          )}

          {/* Success */}
          {status === STATUS.SUCCESS && (
            <div className="glass-card p-8 flex flex-col gap-8 fade-in-up">
              <PlaylistResult
                playlistUrl={playlistUrl}
                playlistName={playlistName}
                trackCount={trackCount}
                onCreateAnother={handleReset}
              />
              {tracks.length > 0 && <TrackList tracks={tracks} />}
            </div>
          )}
        </div>
      </main>
    </div>
  );
}
